In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt

In [2]:
(X_train, y_train), (X_test, y_test) = keras.datasets.cifar10.load_data()

In [3]:
X_train.shape, X_test.shape

((50000, 32, 32, 3), (10000, 32, 32, 3))

In [4]:
classes = ["airplane", "automobile", "bird", "cat", "deer", "dog", "frog", "horse", "ship", "truck"]

In [5]:
y_train.shape

(50000, 1)

In [6]:
y_train[0:5]

array([[6],
       [9],
       [9],
       [4],
       [1]], dtype=uint8)

In [7]:
y_train = y_train.reshape(-1, )

In [8]:
y_train[0:5]

array([6, 9, 9, 4, 1], dtype=uint8)

In [9]:
X_train[0]

array([[[ 59,  62,  63],
        [ 43,  46,  45],
        [ 50,  48,  43],
        ...,
        [158, 132, 108],
        [152, 125, 102],
        [148, 124, 103]],

       [[ 16,  20,  20],
        [  0,   0,   0],
        [ 18,   8,   0],
        ...,
        [123,  88,  55],
        [119,  83,  50],
        [122,  87,  57]],

       [[ 25,  24,  21],
        [ 16,   7,   0],
        [ 49,  27,   8],
        ...,
        [118,  84,  50],
        [120,  84,  50],
        [109,  73,  42]],

       ...,

       [[208, 170,  96],
        [201, 153,  34],
        [198, 161,  26],
        ...,
        [160, 133,  70],
        [ 56,  31,   7],
        [ 53,  34,  20]],

       [[180, 139,  96],
        [173, 123,  42],
        [186, 144,  30],
        ...,
        [184, 148,  94],
        [ 97,  62,  34],
        [ 83,  53,  34]],

       [[177, 144, 116],
        [168, 129,  94],
        [179, 142,  87],
        ...,
        [216, 184, 140],
        [151, 118,  84],
        [123,  92,  72]]

In [10]:
X_train = X_train/255
X_test = X_test/255

In [36]:
y_train_categorical = keras.utils.to_categorical(y_train, num_classes=10, dtype='float32')
y_train_categorical[0:5]

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [37]:
y_test_categorical = keras.utils.to_categorical(y_test, num_classes=10, dtype='float32')

In [61]:
model = keras.Sequential([
    keras.layers.Conv2D(filters=32, kernel_size=(3,3), activation='relu', input_shape = (32,32,3), padding='same'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(filters=48, kernel_size=(3,3), activation='relu', padding='same'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(filters=64, kernel_size=(3,3), activation='relu', padding='same'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(filters=128, kernel_size=(3,3), activation='relu', padding='same'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(filters=256, kernel_size=(3,3), activation='relu', padding='same'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Flatten(),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(10, activation='softmax')
])

callback = keras.callbacks.EarlyStopping(monitor='loss', patience=1)

model.compile(optimizer='adam', loss=keras.losses.CategoricalCrossentropy(), metrics=['accuracy'])

model.fit(X_train, y_train_categorical, epochs=10, callbacks=[callback])

Epoch 1/10


2024-06-18 17:36:14.576180: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


1563/1563 [==============================] - 25s 15ms/step - loss: 1.5343 - accuracy: 0.4311
Epoch 2/10
1563/1563 [==============================] - 24s 15ms/step - loss: 1.0817 - accuracy: 0.6136
Epoch 3/10
1563/1563 [==============================] - 24s 15ms/step - loss: 0.9063 - accuracy: 0.6822
Epoch 4/10
1563/1563 [==============================] - 23s 15ms/step - loss: 0.8022 - accuracy: 0.7204
Epoch 5/10
1563/1563 [==============================] - 24s 15ms/step - loss: 0.7304 - accuracy: 0.7437
Epoch 6/10
1563/1563 [==============================] - 24s 15ms/step - loss: 0.6804 - accuracy: 0.7618
Epoch 7/10
1563/1563 [==============================] - 25s 16ms/step - loss: 0.6472 - accuracy: 0.7754
Epoch 8/10
1563/1563 [==============================] - 24s 15ms/step - loss: 0.6222 - accuracy: 0.7863
Epoch 9/10
1563/1563 [==============================] - 24s 15ms/step - loss: 0.6142 - accuracy: 0.7894
Epoch 10/10
1563/1563 [==============================] - 24s 15ms/step - lo

In [62]:
model.evaluate(X_test, y_test_categorical)

2024-06-18 17:40:20.493610: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


313/313 [==============================] - 3s 8ms/step - loss: 0.8837 - accuracy: 0.7266


[0.8837399482727051, 0.7265999913215637]

In [63]:
y_pred = model.predict(X_test)

 25/313 [=>............................] - ETA: 1s

2024-06-18 17:40:41.545500: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


313/313 [==============================] - 1s 3ms/step
